aplicacion/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views


app_name = 'aplicacion'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('usuario/', include(('modulos.usuario.urls', 'usuario'), namespace='usuario')),
    path('atraccion/', include(('modulos.atraccion.urls', 'atraccion'), namespace='atraccion')),
    path('venta/', include(('modulos.venta.urls','venta'), namespace='venta')),
]

modulos/usuario/urls.py
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from .views import RegistroUsuario, logout_view

app_name = 'usuario'

urlpatterns = [
    path('',
        LoginView.as_view(template_name='usuario/login.html'),
        name='login'
        ),
    path('registrar/',
         RegistroUsuario.as_view(),
         name="registrar"),
    path('logout/',
         logout_view,
         name='logout'),
    path('reset/password_reset',
         PasswordResetView.as_view(), {
             'template_name': 'usuario/password/password_reset_form.html',
             'email_template_name': 'usuario/password/password_reset_email.html'
         },
         name='password_reset'),
    path('password_reset_done',
         PasswordResetDoneView.as_view(), {
             'template_name': 'usuario/password/password_reset_done.html'
         },
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(), {
             'template_name': 'usuario/password/password_reset_confirm.html'
         },
         name='password_reset_confirm'
         ),
    path('reset/done',
         PasswordResetCompleteView.as_view(), {
             'template_name': 'usuario/password/password_reset_complete.html'
         },
         name='password_reset_complete'),
]

apps/usuario/models.py
from django.db import models
from django.contrib.auth.models import User
from proyecto.models import AuditarModel
from datetime import date


# Create your models here.
class Cliente(AuditarModel):
	usuario = models.OneToOneField(User, on_delete=models.CASCADE)
	identificacion = models.PositiveBigIntegerField()
	fecha_nacimiento = models.DateField()
	direccion = models.CharField(max_length=150)
	telefono = models.CharField(max_length=50)

	@property
	def edad(self):
		hoy = date.today()
		return hoy.year - self.fecha_nacimiento.year - ((hoy.month, hoy.day) < (self.fecha_nacimiento.month, self.fecha_nacimiento.day))

modulos/usuario/models.py
from django.db import models
from django.contrib.auth.models import User
from aplicacion.models import AuditarModel
from datetime import date


# Create your models here.
class Cliente(AuditarModel):
	usuario = models.OneToOneField(User, on_delete=models.CASCADE)
	identificacion = models.PositiveBigIntegerField()
	fecha_nacimiento = models.DateField()
	direccion = models.CharField(max_length=150)
	telefono = models.CharField(max_length=50)

	@property
	def edad(self):
		hoy = date.today()
		return hoy.year - self.fecha_nacimiento.year - ((hoy.month, hoy.day) < (self.fecha_nacimiento.month, self.fecha_nacimiento.day))

modulos/usuario/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.forms import widgets
from .models import Cliente
import datetime


class RegistroForm(UserCreationForm, forms.ModelForm):

	class Meta:
		model = User
		fields = [
			'username',
			'first_name',
			'last_name',
			'email',
		]
		labels = {
			'username': 'Nombre de usuario',
			'first_name': 'Nombre',
			'last_name': 'Apellidos',
			'email': 'Correo',
		}
		widgets = {
			'username': forms.TextInput(attrs={'class': 'form-control'}),
			'first_name': forms.TextInput(attrs={'class': 'form-control'}),
			'last_name': forms.TextInput(attrs={'class': 'form-control'}),
			'email': forms.TextInput(attrs={'class': 'form-control'}),
		}
	def __init__(self, *args, **kwargs):
		super(RegistroForm, self).__init__(*args, **kwargs)

		self.fields['password1'].widget.attrs['class'] = 'form-control'
		self.fields['password2'].widget.attrs['class'] = 'form-control'

class ClienteForm(forms.ModelForm):

	class Meta:
		model = Cliente

		fields = [
			'identificacion',
			'fecha_nacimiento',
			'direccion',
			'telefono',
		]

		labels = {
			'identificacion': 'Numero de identificacion',
			'fecha_nacimiento': 'Fecha de nacimiento',
			'direccion': 'Direccion',
			'telefono': 'Numero de telefono'
		}

		YEARS = [x for x in range(datetime.datetime.now().year - 100, datetime.datetime.now().year - 18)]

		widgets = {
			'identificacion': forms.TextInput(attrs={'class': 'form-control'}),
			'fecha_nacimiento': forms.SelectDateWidget(years=YEARS, attrs={'class': 'form-control fecha-control'}),
			'direccion': forms.TextInput(attrs={'class': 'form-control'}),
			'telefono': forms.TextInput(attrs={'class': 'form-control'}),
		}

		# exclude = ('usuario',)

apps/usuario/views.py
from .models import Cliente
from django.shortcuts import render
from django.views.generic import CreateView
from apps.usuario.forms import ClienteForm, RegistroForm
from apps.usuario.models import Cliente
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth import logout


class RegistroUsuario(CreateView):
		model = User

		form_class = RegistroForm
		second_form_class = ClienteForm

		template_name = "usuario/registrar.html"
		success_url = reverse_lazy('aplicacion:index')

		def get_context_data(self, **kwargs):
			context = super(RegistroUsuario, self).get_context_data(**kwargs)
			if 'form' not in context:
				context['form'] = self.form_class(self.request.GET)
			if 'form2' not in context:
				context['form2'] = self.second_form_class(self.request.GET)
			return context

		# Get = traer, post = guardar, put = actualizar (completo), patch actualizar (parcial) y delete (borrar)
		def post(self, request, *args, **kwargs):
			self.object = self.get_object

			formulario_usuario = self.form_class(request.POST) # Formulario: Usuario - traer informacion que tenia en el formulario
			formulario_cliente = self.second_form_class(request.POST)

			if formulario_usuario.is_valid() and formulario_cliente.is_valid():
				usuario = formulario_usuario.save(commit=False)
				cliente = formulario_cliente.save(commit=False)

				#	este try control de errores si hay un error  va ejecutar la parte del except (linea 48)
				try:
					usuario.save()

					cliente.usuario = usuario
					cliente.save()

					# si el usuario se registra exitosamente entonces lo va a dirigir a el index(home)
					return HttpResponseRedirect(self.get_success_url())
				except Exception as e:
					# print imprime en la terminal lo que se le envie (le dicen logs)
					print('error', e)

			# si el formulario no esta correcto lo va a dirigir a la data que el usario ya tenia para que vuelva a ingresar los datos correctamente 
			return self.render_to_response(self.get_context_data(form=formulario_usuario, form2=formulario_cliente))

def logout_view(request):
    # Desconectar usuario
    logout(request)

    # Redirigir a la página de inicio
    return HttpResponseRedirect(reverse_lazy('aplicacion:index'))

modulos/usuario/views.py
from .models import Cliente
from django.shortcuts import render
from django.views.generic import CreateView
from modulos.usuario.forms import ClienteForm, RegistroForm
from modulos.usuario.models import Cliente
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth import logout


class RegistroUsuario(CreateView):
		model = User

		form_class = RegistroForm
		second_form_class = ClienteForm

		template_name = "usuario/registrar.html"
		success_url = reverse_lazy('index')

		def get_context_data(self, **kwargs):
			context = super(RegistroUsuario, self).get_context_data(**kwargs)
			if 'form' not in context:
				context['form'] = self.form_class(self.request.GET)
			if 'form2' not in context:
				context['form2'] = self.second_form_class(self.request.GET)
			return context

		# Get = traer, post = guardar, put = actualizar (completo), patch actualizar (parcial) y delete (borrar)
		def post(self, request, *args, **kwargs):
			self.object = self.get_object

			formulario_usuario = self.form_class(request.POST) # Formulario: Usuario - traer informacion que tenia en el formulario
			formulario_cliente = self.second_form_class(request.POST)

			if formulario_usuario.is_valid() and formulario_cliente.is_valid():
				usuario = formulario_usuario.save(commit=False)
				cliente = formulario_cliente.save(commit=False)

				#	este try control de errores si hay un error  va ejecutar la parte del except (linea 48)
				try:
					usuario.save()

					cliente.usuario = usuario
					cliente.save()

					# si el usuario se registra exitosamente entonces lo va a dirigir a el index(home)
					return HttpResponseRedirect(self.get_success_url())
				except Exception as e:
					# print imprime en la terminal lo que se le envie (le dicen logs)
					print('error', e)

			# si el formulario no esta correcto lo va a dirigir a la data que el usario ya tenia para que vuelva a ingresar los datos correctamente 
			return self.render_to_response(self.get_context_data(form=formulario_usuario, form2=formulario_cliente))

def logout_view(request):
    # Desconectar usuario
    logout(request)

    # Redirigir a la página de inicio
    return HttpResponseRedirect(reverse_lazy('index'))

templates/usuario/antiguo-Registrar.html
<!--este (if form.errors) me dice que si hay un error  -->
{% if form.errors %}
{% for campo in form %}
  {% for error in campo.errors %}
      <div class="alert alert-danger">
          <strong>{{ campo.label }} - {{ error | escape }}</strong>
      </div>
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
        <strong>{{campo.label}} - { error | escape }} </strong>
    </div>
  {% endfor %}
{% endfor %}
{% endif %}

<div class="row">
<div class="col-md-8 col-md-offset-2">
  <div class="form-group">
    <label for="{{form.first_name.name}}">{{form.first_name.label}}</label>
    {{ form.first_name }}
  </div>
</div>
</div>
<div class="row">
<div class="col-md-8 col-md-offset-2">
  <div class="form-group">
    <label>Apellidos</label>
    {{ form.last_name }}
  </div>
</div>
</div>
<div class="row">
<div class="col-md-8 col-md-offset-2">
  <div class="form-group">
    <label>Nombre de usuario</label>
    <input class="form-control" type="text" name="username" />
  </div>
</div>
</div>
<div class="row">
<div class="col-md-8 col-md-offset-2">
  <div class="form-group">
    <label>Correo</label>
    <input class="form-control" type="text" name="email" />
  </div>
</div>
</div>
<div class="row">
<div class="col-md-8 col-md-offset-2">
  <div class="form-group">
    <label>Contraseña</label>
    <input class="form-control" type="password" name="password1" />
  </div>
</div>
</div>
<div class="row">
<div class="col-md-8 col-md-offset-2">
  <div class="form-group">
    <label>Confirmar contraseña</label>
    <input class="form-control" type="password" name="password2" />
  </div>
</div>
</div>

<div class="row">
<div class="col-md-8 col-md-offset-2">
  <div class="form-group">
    <button class="btn btn-primary" type="submit">Guardar</button>
  </div>
</div>
</div>

templates/usuario/index.html
{% extends 'base/base.html' %}

{% block titulo%}
login
{% endblock %}

{% block content %}
<form method="post">
	{% csrf_token %}
	 <div class="row">
    	<div class="col-md-6 col-md-offset-3">
    		<div class="form-group">
        		<label for="username">Nombre de usuario:</label>
        		<input class="form-control" type="text" name="username">
    	   </div>
        </div>
    </div>
    <div class="row">
    	<div class="col-md-6 col-md-offset-3">
    		<div class="form-group">
        		<label for="username">Contraseña:</label>
        		<input class="form-control" type="password" name="password">
    	   </div>
        </div>
    </div>
    <div class="row">
    	<div class="col-md-6 col-md-offset-3">
    		<div class="form-group">
						<a href="{% url 'usuario:password_reset' %}">Olvidé mi contraseña</a>
						||
						<a href="{% url 'usuario:registrar' %}">Registrarte</a>
						||
						<a href="{% url 'aplicacion:index' %}">App</a>
        		<input class="btn btn-primary" type="submit" value="Ingresar">
    	   </div>
        </div>
    </div>
</form>


{% endblock %}

templates/usuario/login-.html
{% extends 'base/base.html' %}

{% block titulo%}
login
{% endblock %}

{% block content %}
<form method="post">
	{% csrf_token %}
	 <div class="row">
    	<div class="col-md-6 col-md-offset-3">
    		<div class="form-group">
        		<label for="username">Nombre de usuario:</label>
        		<input class="form-control" type="text" name="username">
    	   </div>
        </div>
    </div>
    <div class="row">
    	<div class="col-md-6 col-md-offset-3">
    		<div class="form-group">
        		<label for="username">Contraseña:</label>
        		<input class="form-control" type="password" name="password">
    	   </div>
        </div>
    </div>
    <div class="row">
    	<div class="col-md-6 col-md-offset-3">
    		<div class="form-group">
						<a href="{% url 'usuario:registrar' %}">Registrarte</a>
						||
						<a href="{% url 'index' %}">App</a>
        		<input class="btn btn-primary" type="submit" value="Ingresar">
    	   </div>
        </div>
    </div>
</form>


{% endblock %}

templates/usuario/login.html
<!--<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>-->
<!------ Include the above in your HEAD tag ---------->
{% extends 'base/base.html' %}
{% block titulo%}
login
{% endblock %}

{% block content %}
<form method="post">
{% csrf_token %}
    <div id="login">
        <h3 class="text-center text-white pt-5 ">por que queremos que todos tus dias sena unicos</h3>
        <div class="container">
            <div id="login-row" class="row justify-content-center align-items-center">
                <div id="login-column" class="col-md-6">
                    <div id="login-box" class="col-md-12">
                        <div id="login-form" class="form" action="" method="post">
                            <h3 class="text-center text-info">Divertiland</h3>
                            <div class="form-group">
                                <label for="username" class="text-info">Nombre de usuario:</label><br>
                                <input type="text" name="username" id="username" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="password" class="text-info">Contraseña</label><br>
                                <input type="password" name="password" id="password" class="form-control">
                            </div>
                            <div class="form-group">
                                <a href="{% url 'usuario:registrar' %}">Registrarte</a>
                                ||
                                <a href="{% url 'index' %}">App</a>
                                <input class="btn btn-primary" type="submit" value="Ingresar">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

templates/usuario/registrar.html
{% extends 'base/base.html' %}

{% block titulo %}Registrar{% endblock %}

{% block content %}
<form method="post">
  {% csrf_token %}
  {% if form.errors %}
    {% for campo in form %}
      {% for error in campo.errors %}
          <div class="alert alert-danger">
              <strong>{{ campo.label }} - {{ error | escape }}</strong>
          </div>
      {% endfor %}
      {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{campo.label}} - { error | escape }} </strong>
        </div>
      {% endfor %}
    {% endfor %}
  {% endif %}

  {{form}}
  {{form2}}

  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="form-group">
        <button class="btn btn-primary" type="submit">Guardar</button>
      </div>
    </div>
    </div>
</form>
<style>
  label {
    font-weight: bold;
    display: block;
    margin-top: 1rem;
    margin-bottom: .5rem;
  }

  .fecha-control {
    width: 15%;
    display: inline-block;
  }
</style>
{% endblock %}