aplicacion/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views


app_name = 'aplicacion'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('usuario/', include(('modulos.usuario.urls', 'usuario'), namespace='usuario')),
    path('atraccion/', include(('modulos.atraccion.urls', 'atraccion'), namespace='atraccion')),
    path('venta/', include(('modulos.venta.urls','venta'), namespace='venta')),
]

modulos/venta/urls.py
from django.urls import path, include
from . import views

# Cart Urls
urlpatterns = [
    path('ver/<int:pk>/', views.DetalleCarrito.as_view(), name='carrito'),
    path('agregar/<int:pk>/', views.agregar_a_carrito, name='agregar-a-carrito'),
    path('eliminar/<int:pk>/', views.eliminar_de_carrito, name='eliminar-de-carrito'),
    path('historico/', views.HistorialCompras.as_view(), name='historial'),
    path('admin/pagado/<int:pk>/', views.marcar_pagado, name='pagado'),
    path('admin/eliminar/<int:pk>/', views.eliminar_carrito, name='eliminar-carrito'),
    path('admin/historico/', views.AdminHistorialCompras.as_view(), name='historial-admin'),
]

apps/venta/models.py
from proyecto.models import AuditarModel
from django.db import models
from datetime import datetime
from proyecto.models import AuditarModel
from apps.atraccion.models import Atraccion
from apps.usuario.models import Cliente

# Create your models here.
# clase/modelo
class Carrito(AuditarModel):
    # atributos
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    pagado = models.BooleanField(default=False)


class ItemCarrito(AuditarModel):
    atraccion = models.ForeignKey(Atraccion, on_delete=models.CASCADE)
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE)

    def __str__(self):
        return  self.carrito.cliente.usuario.username + " - " + self.atraccion.nombre

modulos/venta/models.py
from django.db import models
from datetime import datetime
from aplicacion.models import AuditarModel
from modulos.atraccion.models import Atraccion
from modulos.usuario.models import Cliente

# Create your models here.
# clase/modelo
class Carrito(AuditarModel):
    # atributos
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    pagado = models.BooleanField(default=False)


class ItemCarrito(AuditarModel):
    atraccion = models.ForeignKey(Atraccion, on_delete=models.CASCADE)
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE)

    def __str__(self):
        return  self.carrito.cliente.usuario.username + " - " + self.atraccion.nombre


apps/venta/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from apps.atraccion.models import Atraccion
from .models import Carrito, ItemCarrito
from django.contrib.auth.mixins import PermissionRequiredMixin
from apps.usuario.models import Cliente

#Detalles de el carrito 
class DetalleCarrito(DetailView):
    model = Carrito
    template_name='venta/detalle_carrito.html'
    context_object_name = 'venta'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['items'] = ItemCarrito.objects.filter(carrito=self.object)
        return context


    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if not self.request.user.is_authenticated:
            return redirect('aplicacion:index')

        if not self.object.cliente.usuario.id == self.request.user.id:
            return redirect('aplicacion:index')

        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

#agregara a el carrito las atraciones 
def agregar_a_carrito(request, pk):
    atraccion = Atraccion.objects.get(pk=pk)
    cliente = Cliente.objects.get(usuario_id = request.user.id)
    carrito = Carrito.objects.filter(cliente = cliente, pagado = False).first()
    if not carrito:
        carrito = Carrito.objects.create(cliente = cliente)
        carrito.save()
    carritoItem = ItemCarrito.objects.create(carrito = carrito, atraccion = atraccion)
    carritoItem.save()
    return redirect('venta:carrito', pk = carrito.pk)

#eliminar de el carrito 
def eliminar_de_carrito(request, pk):
    carritoItem = ItemCarrito.objects.get(id = pk)
    carrito = carritoItem.carrito.pk
    if carritoItem:
        carritoItem.delete()
    return redirect('venta:carrito', pk = carrito)

modulos/venta/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from modulos.atraccion.models import Atraccion
from .models import Carrito, ItemCarrito
from django.contrib.auth.mixins import PermissionRequiredMixin
from modulos.usuario.models import Cliente

# Historial Compras
class HistorialCompras(ListView):
    paginate_by = 3
    template_name='venta/historial_compras.html'
    context_object_name = 'historial'
    def get_queryset(self):
        cliente = Cliente.objects.get(usuario_id = self.request.user.id)
        queryset = Carrito.objects.order_by('-fecha_creacion').filter(cliente = cliente)
        return queryset

#Detalles de el carrito 
class DetalleCarrito(DetailView):
    model = Carrito
    template_name='venta/detalle_carrito.html'
    context_object_name = 'venta'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['items'] = ItemCarrito.objects.filter(carrito=self.object)
        return context


    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if not self.request.user.is_authenticated:
            return redirect('index')

        if (not self.object.cliente.usuario.id == self.request.user.id) and (not self.request.user.is_staff):
            return redirect('index')

        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


class AdminHistorialCompras(ListView):
    paginate_by = 3
    template_name='venta/historial_compras.html'
    context_object_name = 'historial'
    def get_queryset(self):
        queryset = Carrito.objects.order_by('-fecha_creacion').all()
        return queryset

#agregara a el carrito las atraciones 
def agregar_a_carrito(request, pk):
    atraccion = Atraccion.objects.get(pk=pk)
    cliente = Cliente.objects.get(usuario_id = request.user.id)
    carrito = Carrito.objects.filter(cliente = cliente, pagado = False).first()
    if not carrito:
        carrito = Carrito.objects.create(cliente = cliente)
        carrito.save()
    carritoItem = ItemCarrito.objects.create(carrito = carrito, atraccion = atraccion)
    carritoItem.save()
    return redirect('venta:carrito', pk = carrito.pk)

#eliminar de el carrito 
def eliminar_de_carrito(request, pk):
    carritoItem = ItemCarrito.objects.get(id = pk)
    carrito = carritoItem.carrito.pk
    if carritoItem:
        carritoItem.delete()
    return redirect('venta:carrito', pk = pk)

def marcar_pagado(request, pk):
    if request.user.is_staff:
        carrito = Carrito.objects.get(pk = pk)
        carrito.pagado = not carrito.pagado
        carrito.save()
    return redirect('venta:carrito', pk = pk)

def eliminar_carrito(request, pk):
    if request.user.is_staff:
        carrito = Carrito.objects.get(pk = pk)
        if carrito:
            carrito.delete()
    return redirect('index')

templates/venta/detalle_carrito.html
{% extends 'base/base.html' %}

{% block titulo%}
  Detalle
{% endblock %}

{% block content %}
<h1>hola mundo </h1>
<p>{{ object.pagado }}</p>
<p>{{ object | pprint }}</p>
<p>{{ object.cliente | pprint }}</p>
<p>{{ object.cliente.identificacion }}</p>
<p>{{ object.cliente.usuario.username }}</p>

{% if items %}
  <div class="card-columns">
    {% for item in items %}
    <a href="{% url 'venta:eliminar-de-carrito' item.pk %}">
      Eliminar
    </a>
    <p>{{ item.atraccion.nombre }}</p>
    <p>{{ item.cantidad }}</p>

    {% endfor %}
  </div>
{% else %}
  <h1>No hay Items añadidos</h1>
{% endif %}

{% if user.is_staff %}
  <a href="{% url 'venta:eliminar-carrito' object.pk %}" class="nav-link">
    Eliminar Carrito
  </a>
  {% if object.pagado %}
      <a href="{% url 'venta:pagado' object.pk %}" class="nav-link">
        Marcar como No Pagado
      </a>
    {% else %}
      <a href="{% url 'venta:pagado' object.pk %}" class="nav-link">
        Marcar como Pagado
      </a>
    {% endif %}
  {% endif %}
{% endblock%}

templates/venta/historial_compras.html
{% extends 'base/base.html' %}
{%block content%}
<section>
  <h2 class="">Historial</h2>
  <div>
    {% if  object_list %}
    <div class="card-columns">
      {% for carrito in object_list %}
      <a href="{% url 'venta:carrito' carrito.pk %}">
        <div class="card">
          <div class="card-body">
            {% if not carrito.pagado %}
              <small
                style="position: absolute; left: 50%; transform: translate(-50%, -50%); bottom: 0; color: #4caf50; font-style: oblique; font-weight: bold;"
              >
                Carrito Actual
              </small>
            {% endif %}
            <p>
              Carrito número {{ carrito.pk}} 
              {% if user.is_staff %}
                de {{ carrito.cliente.usuario.username }}
              {% endif %}
              creado el: </p>
            <h5 class="card-title">{{ carrito.fecha_creacion }}</h5>
          </div>
        </div>
      </a>
      {% endfor %}
    </div>
    {% else %}
    <h1>No hay historial de carrito </h1>
    {% endif %}
  </div>

  <ul class="paginador">
    <li>
      {% if page_obj.has_previous %}
      <a class="botoneditar" href="?page={{ page_obj.previous_page_number }}">
        Atras
      </a>
      {% endif %}
    </li>
    <li>
      {% if page_obj.has_next %}
      <a class="botoneliminar" href="?page={{ page_obj.next_page_number }}">
        Siguiente
      </a>
      {% endif %}
    </li>
  </ul>
</section>
{% endblock%}