aplicacion/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views


app_name = 'aplicacion'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('usuario/', include(('modulos.usuario.urls', 'usuario'), namespace='usuario')),
    path('atraccion/', include(('modulos.atraccion.urls', 'atraccion'), namespace='atraccion')),
    path('venta/', include(('modulos.venta.urls','venta'), namespace='venta')),
]

modulos/atraccion/urls.py
from django.urls import path
from .views import Lista, Crear, Detalle, Eliminar, Editar

urlpatterns = [
    path('', Lista.as_view(), name='lista'),
    path('<int:pk>/', Detalle.as_view(), name='detalle'),
    path('editar/<int:pk>/', Editar, name='editar'),
    path('crear/', Crear, name='crear'),
    path('eliminar/<int:pk>/', Eliminar, name='eliminar'),
]

modulos/venta/urls.py
from django.urls import path, include
from . import views

# Cart Urls
urlpatterns = [
    path('ver/<int:pk>/', views.DetalleCarrito.as_view(), name='carrito'),
    path('agregar/<int:pk>/', views.agregar_a_carrito, name='agregar-a-carrito'),
    path('eliminar/<int:pk>/', views.eliminar_de_carrito, name='eliminar-de-carrito'),
    path('historico/', views.HistorialCompras.as_view(), name='historial'),
    path('admin/pagado/<int:pk>/', views.marcar_pagado, name='pagado'),
    path('admin/eliminar/<int:pk>/', views.eliminar_carrito, name='eliminar-carrito'),
    path('admin/historico/', views.AdminHistorialCompras.as_view(), name='historial-admin'),
]

apps/atraccion/models.py
from django.db import models
from proyecto.models import AuditarModel

class Atraccion (AuditarModel):
	nombre = models.CharField(max_length=100)
	precio = models.DecimalField(null=False, decimal_places=20, max_digits=100)
	estado = models.BooleanField(default=True,blank=False)
	descripcion = models.CharField(max_length=1200)
	imagen = models.CharField(max_length=200)

modulos/atraccion/models.py
from django.db import models
from aplicacion.models import AuditarModel

class Atraccion (AuditarModel):
	nombre = models.CharField(max_length=100)
	precio = models.DecimalField(null=False, decimal_places=20, max_digits=100)
	estado = models.BooleanField(default=True,blank=False)
	descripcion = models.CharField(max_length=1200)
	imagen = models.CharField(max_length=200)

modulos/atraccion/forms.py
from django import forms
from .models import Atraccion


class CrearForm(forms.ModelForm):
    class Meta:
        model = Atraccion
        fields = "__all__"

apps/atraccion/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from .models import Atraccion
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse_lazy
from .forms import CrearForm


class Lista(ListView):
    queryset = Atraccion.objects.all().filter(estado=True)
    template_name = 'atraccion/lista.html'
    paginate_by = 6


class Detalle(DetailView):
    model = Atraccion
    template_name = 'atraccion/detalle.html'


def Crear(request):
    if request.method == 'POST':
        form = CrearForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('atraccion:lista')
    form = CrearForm(instance=Atraccion)  # creacionde el formulario

    # retorno a el formulario de html con el formulario creado
    return render(request, 'atraccion/crear.html', {'form': form})


def Editar(request, pk, template_name='atraccion/editar.html'):
    atraccion = get_object_or_404(Atraccion, pk=pk)
    form = CrearForm(request.POST or None, instance=atraccion)
    if form.is_valid():
        form.save()
        return redirect('atraccion:lista')
    return render(request, template_name, {'form': form})


def Eliminar(request, pk, template_name='atraccion/eliminar.html'):
    atraccion = get_object_or_404(Atraccion, pk=pk)
    if request.method == 'POST':
        atraccion.delete()
        return redirect('atraccion:lista')
    return render(request, template_name, {'object': atraccion})

modulos/atraccion/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from .models import Atraccion
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse_lazy
from .forms import CrearForm


class Lista(ListView):
    queryset = Atraccion.objects.all().filter(estado=True)
    template_name = 'atraccion/lista.html'
    paginate_by = 3


class Detalle(DetailView):
    model = Atraccion
    template_name = 'atraccion/detalle.html'


def Crear(request):
    if request.method == 'POST':
        form = CrearForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('atraccion:lista')
    form = CrearForm(instance=Atraccion)  # creacionde el formulario

    # retorno a el formulario de html con el formulario creado
    return render(request, 'atraccion/crear.html', {'form': form})


def Editar(request, pk, template_name='atraccion/editar.html'):
    atraccion = get_object_or_404(Atraccion, pk=pk)
    form = CrearForm(request.POST or None, instance=atraccion)
    if form.is_valid():
        form.save()
        return redirect('atraccion:lista')
    return render(request, template_name, {'form': form})


def Eliminar(request, pk, template_name='atraccion/eliminar.html'):
    atraccion = get_object_or_404(Atraccion, pk=pk)
    if request.method == 'POST':
        atraccion.delete()
        return redirect('atraccion:lista')
    return render(request, template_name, {'object': atraccion})

templates/atraccion/crear.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container-fluid">
  <div class="row">
      <div class="col-md-1 col-xs-1 col-sm-1"></div>

      <div class="col-md-10 col-xs-10 col-sm-10 ">
          <br />
          <h6 style="text-align:center;">
              <b color="red"> Todos los campos son requeridos</b>
          </h6>
      </div>
      <div class="col-md-1 col-xs-1 col-sm-1">
      </div>
  </div>
  <div class="row">
      <div class="col-md-1 col-xs-1 col-sm-1"></div>
      <div class="col-md-10 col-xs-10 col-sm-10">
          <form method="post" novalidate>
              {% csrf_token %}
              {% for hidden_field in form.hidden_fields %}
              {{ hidden_field }}
              {% endfor %}
              {% for field in form.visible_fields %}
              <div class="form-group">
                  {{ field.label_tag }}
                  {% render_field field class="form-control" %}
                  {% if field.help_text %}
                  <small class="form-text text-muted">{{ field.help_text }}</small>
                  {% endif %}
              </div>
              {% endfor %}
              <button type="submit" class="btn btn-primary">Enviar</button>
          </form>
          <br>
      </div>
      <div class="col-md-1 col-xs-1 col-sm-1"></div>
  </div>
</div>
{% endblock %}

templates/atraccion/detalle.html
{% extends 'base/base.html' %}
{% block content %}
    <div class="detallesproducto container">

        <img src="{{ object.imagen }}" alt="" class="imgs"/>
        <h1 class="titulodetalle">{{ object.nombre }}</h1>
        <p class="textodetalle">{{ object.descripcion }}</p>
        <h5 class="preciodetalle">{{ object.precio }}</h5>

    </div>

    {% if user.is_authenticated and not user.is_staff %}
        <span class="editardetalle">
            <a class="botonagregar" href="{% url 'venta:agregar-a-carrito' atraccion.pk %}">Agregar al Carrito</a>
        </span>
    {% endif %}
    {% if user.is_staff %}
        <div  class="editardetalle" >
        <a class="botoneditar" href="{% url 'atraccion:editar' atraccion.pk %}">Editar</a>
        <a class="botoneliminar" href="{% url 'atraccion:eliminar' atraccion.pk %}">Eliminar</a>
        </div>
    {% endif %}
{% endblock %}

templates/atraccion/editar.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container-fluid">
  <div class="row">
      <div class="col-md-1 col-xs-1 col-sm-1"></div>
      <div class="col-md-10 col-xs-10 col-sm-10 ">
          <br />
          <h6 style="text-align:center;">
              <b color="red"> todos los campos son obligatorios</b>
          </h6>
      </div>
      <div class="col-md-1 col-xs-1 col-sm-1">
      </div>
  </div>
  <div class="row">
      <div class="col-md-1 col-xs-1 col-sm-1"></div>
      <div class="col-md-10 col-xs-10 col-sm-10">
          <form method="post" novalidate>
              {% csrf_token %}
              {% for hidden_field in form.hidden_fields %}
              {{ hidden_field }}
              {% endfor %}
              {% for field in form.visible_fields %}
              <div class="form-group">
                  {{ field.label_tag }}
                  {% render_field field class="form-control" %}
                  {% if field.help_text %}
                  <small class="form-text text-muted">{{ field.help_text }}</small>
                  {% endif %}
              </div>
              {% endfor %}
              <button type="submit" class="btn btn-primary">Guardar</button>
          </form>
          <br>
      </div>
      <div class="col-md-1 col-xs-1 col-sm-1"></div>
  </div>
</div>
{% endblock %}

templates/atraccion/eliminar.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container">
  <div class="row"></div>
  <br />
  <div class="row">
      <div class="col-md-2 col-xs-2 col-sm-2"></div>
      <div class="col-md-10 col-xs-10 col-sm-10">
          <form method="post">
              {% csrf_token %}
              <div class="form-row">
                  <div class="alert alert-warning">
                      Estas seguro que deseas eliminar el {{ object.nombre }}?
                  </div>
              </div>
              <button type="submit" class="btn btn-danger">
                  <span class="glyphicon glyphicon-trash">Eliminar</span>
              </button>
          </form>
      </div>
  </div>
</div>
{% endblock %}

templates/atraccion/lista.html
{% extends 'base/base.html' %}
{%block content%}

<section class="row products-masonry-container">
  <div class="container atracciones">
    <div class="text-center atraccion">
      <div class="estilostitulo">
        <h2 class=" tituloatraccion ">Atracciones</h2>
      <h3 class="section-subheading">
        que la aventura y la diversion te acompañe
      </h3>
      </div>
    </div>
  <div class="col">
    <div class="products-masonry">
      <div class="tab-content">
        <div class="tab-pane fade show active" id="todos">
          <!--el condicional especifica que si object list es mayor a uno
          entonces me va a pinta el ciclo for de lo contario va a decior que no
          hay registros de la atracccion-->
          {% if object_list %}
          <div class="card-columns">
            {% for atraccion in object_list %}
            <a href="{% url 'atraccion:detalle' atraccion.pk %}">
              <div class="card">
                <img
                  src="{{ atraccion.imagen }}"
                  alt="imagen de la atraccion "
                  class="card-img-top"
                />
                <div class="card-body">
                  <h5 class="card-title">{{ atraccion.nombre }}</h5>
                  <p class="card-text">
                    ${{ atraccion.precio | floatformat:"0" }}
                  </p>
                </div>
              </div>
            </a>

            {% endfor %}
          </div>
          {% else %}
          <h1>No hay registros de Atracciones</h1>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</section>
<ul class="paginador">
  <li>
    {% if page_obj.has_previous %}
    <a class="botoneditar" href="?page={{ page_obj.previous_page_number }}">Atras</a>
    {% endif %}
  </li>
  <li>
    {% if page_obj.has_next %}
    <a class="botoneliminar" href= "?page={{ page_obj.next_page_number }}">Siguiente</a>
    {% endif %}
  </li>
</ul>
{% if user.is_staff %}
<div class="container">
  <a href="{% url 'atraccion:crear' %}" class="btn btn-primary" type="submit"
    >crear atraccion</a
  >
</div>
{% endif %}
{% endblock%}