aplicacion/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views


app_name = 'aplicacion'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('usuario/', include(('modulos.usuario.urls', 'usuario'), namespace='usuario')),
    path('atraccion/', include(('modulos.atraccion.urls', 'atraccion'), namespace='atraccion')),
    path('venta/', include(('modulos.venta.urls','venta'), namespace='venta')),
]

modulos/atraccion/urls.py
from django.urls import path
from .views import Lista, Crear, Detalle, Eliminar, Editar

urlpatterns = [
    path('', Lista.as_view(), name='lista'),
    path('<int:pk>/', Detalle.as_view(), name='detalle'),
    path('editar/<int:pk>/', Editar, name='editar'),
    path('crear/', Crear, name='crear'),
    path('eliminar/<int:pk>/', Eliminar, name='eliminar'),
]

modulos/usuario/urls.py
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from .views import RegistroUsuario, logout_view

app_name = 'usuario'

urlpatterns = [
    path('',
        LoginView.as_view(template_name='usuario/login.html'),
        name='login'
        ),
    path('registrar/',
         RegistroUsuario.as_view(),
         name="registrar"),
    path('logout/',
         logout_view,
         name='logout'),
    path('reset/password_reset',
         PasswordResetView.as_view(), {
             'template_name': 'usuario/password/password_reset_form.html',
             'email_template_name': 'usuario/password/password_reset_email.html'
         },
         name='password_reset'),
    path('password_reset_done',
         PasswordResetDoneView.as_view(), {
             'template_name': 'usuario/password/password_reset_done.html'
         },
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(), {
             'template_name': 'usuario/password/password_reset_confirm.html'
         },
         name='password_reset_confirm'
         ),
    path('reset/done',
         PasswordResetCompleteView.as_view(), {
             'template_name': 'usuario/password/password_reset_complete.html'
         },
         name='password_reset_complete'),
]

modulos/venta/urls.py
from django.urls import path, include
from . import views

# Cart Urls
urlpatterns = [
    path('ver/<int:pk>/', views.DetalleCarrito.as_view(), name='carrito'),
    path('agregar/<int:pk>/', views.agregar_a_carrito, name='agregar-a-carrito'),
    path('eliminar/<int:pk>/', views.eliminar_de_carrito, name='eliminar-de-carrito'),
    path('historico/', views.HistorialCompras.as_view(), name='historial'),
    path('admin/pagado/<int:pk>/', views.marcar_pagado, name='pagado'),
    path('admin/eliminar/<int:pk>/', views.eliminar_carrito, name='eliminar-carrito'),
    path('admin/historico/', views.AdminHistorialCompras.as_view(), name='historial-admin'),
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% block extrastatic %} {% endblock %}
    <title>Divertyland - {% block titulo %}Inicio{% endblock %}</title>
    <link
      rel="shortcut icon"
      href="static/img/tobogan.png"
      type="image/x-icon"
    />
    {% load bootstrap4 %} {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}" />
  </head>
  <body>
    {% block navbar %} 
    {% include 'base/menu.html'%}
    {% endblock %} 

{% block content %}

    <main class="container contenidopagina">
      <section class="page-section">
        <div class="container">
          <div class="text-center">
            <img src="static/img/tobogan.png" alt="Tobogan" class="imagenbase">
            <h3 class="section-subheading parrafo ">
              No te querrás perder todas las atracciones que tenemos disponibles para ti, vivirás una experiencia maravillosa rodeada de tus seres más amados, te ofrecemos las mejores atracciones acuáticas veras y conocerás especies que no habías visto antes aprenderás con nosotros  sobre nuestro hermoso mariposario 
            </h3>
          </div>
          <div class="row text-center">
            <div class="col-md-4">
              <span class="fa-stack fa-4x">
                <img src="static/img/amigos.jpg" class="imagenes" alt="amigos">
              </span>
              <h4 class="my-3">amigos </h4>
              <p class="text-muted">
                divertirse con los amigos es unico 
              </p>
            </div>
            <div class="col-md-4">
              <span class="fa-stack fa-4x">
                <img src="static/img/familias.jpg" class="imagenes" alt="familias">
              </span>
              <h4 class="my-3">familia</h4>
              <p class="text-muted">
              divertirse con la famial es uan gran muestra de amor y de apoyo 
              </p>
            </div>
            <div class="col-md-4">
              <span class="fa-stack fa-4x">
                <img src="static/img/parejas.jpg" class="imagenes" alt="parejas" >
              </span>
              <h4 class="my-3">relaciones</h4>
              <p class="text-muted">
                que mejor manera de divertise con tu pareja es  estando juntos 
              </p>
            </div>
          </div>
        </div>
      </section>
    </main>

{% endblock %}
     
    {% block footer %} 
    {% include 'base/footer.html'%} 
    {% endblock %}
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block extrajs %} {% endblock %} {% bootstrap_javascript jquery='full' %}
  </body>
</html>

templates/base/footer.html
{% load static %}
<footer class="footer py-4 colores">
  <div class="container">
    <div class="row align-items-center derechos">
      <div class="col-lg-4 text-lg-start">
        <h3 class="titulo">nos encanta ver te feliz</h3>
      </div>
      <div class="col-lg-4 my-3 my-lg-0">
        <a
          href="https://www.facebook.com/mariacamila.lopez.16752754/"
          class="text-white mr-1"
        >
          <i class="fab fa-facebook-f"></i>
          <img
            src="{% static 'img/facebook.png' %}"
            alt="facebook"
            class="image"
          />
        </a>
        <a href="https://www.instagram.com/" class="text-white mr-1">
          <i class="fab fa-instagram"></i>
          <img
            src="{% static 'img/instagram.png'%}"
            alt="instagram"
            class="image"
          />
        </a>
        <a href=" https://wa.link/8ixv3u" class="text-white">
          <i class="fab fa-whatsapp"></i>
          <img
            src="{% static 'img/whatsapp.png' %}"
            alt="whatsapp"
            class="image"
          />
        </a>
      </div>
      <div class="col-lg-4 text-lg-end">
        <small>&copy; Todos los derechos reservados</small>
      </div>
    </div>
  </div>
</footer>

templates/base/footer1.html
{% load static %}

<footer class="colores">
  <div>
        <ul class="listar">
          <li class="nav-item">
            <a href="{% url 'index' %}" class="nav-link ">Home</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'atraccion:lista' %}" class="nav-link ">atracciones</a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link ">Nosotros</a>
          </li>
        </ul>
  </div>

    <div class=" text-center ">
        <a href="https://www.facebook.com/mariacamila.lopez.16752754/" class="text-white mr-1">
          <i class="fab fa-facebook-f"></i>
          <img src="{% static 'img/facebook.png' %}" alt="facebook"class="image">
        </a>
        <a href="https://www.instagram.com/" class="text-white mr-1">
          <i class="fab fa-instagram"></i>
          <img src="{% static 'img/instagram.png'%}" alt="instagram" class="image">
        </a>
        <a href=" https://wa.link/8ixv3u" class="text-white">
          <i class="fab fa-whatsapp"></i>
          <img src="{% static 'img/whatsapp.png' %}" alt="whatsapp"class="image">
        </a>
    </div>
    <div class="piedepagina">
      <h2 class="titulo">nos encanta ver te feliz  </h2>
      <div class="tex">
    <div class=" align-items-center py-3">
      <p class="derechos">
        <small>&copy; Todos los derechos reservados</small>
      </p>
    </div>
  </div>
</footer>

templates/base/footers.html
{% load static %}

<footer class="colores">
  <div>
        <ul class="listar">
          <li class="nav-item">
            <a href="{% url 'index' %}" class="nav-link ">Home</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'atraccion:lista' %}" class="nav-link ">atracciones</a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link ">Nosotros</a>
          </li>
        </ul>
  </div>

    <div class=" text-center ">
        <a href="https://www.facebook.com/mariacamila.lopez.16752754/" class="text-white mr-1">
          <i class="fab fa-facebook-f"></i>
          <img src="{% static 'img/facebook.png' %}" alt="facebook"class="image">
        </a>
        <a href="https://www.instagram.com/" class="text-white mr-1">
          <i class="fab fa-instagram"></i>
          <img src="{% static 'img/instagram.png'%}" alt="instagram" class="image">
        </a>
        <a href=" https://wa.link/8ixv3u" class="text-white">
          <i class="fab fa-whatsapp"></i>
          <img src="{% static 'img/whatsapp.png' %}" alt="whatsapp"class="image">
        </a>
    </div>
    <div class="piedepagina">
      <h3 class="titulo">nos encanta ver te feliz  </h3>
      <div class="tex">
    <div class=" align-items-center py-3">
      <p class="derechos">
        <small>&copy; Todos los derechos reservados</small>
      </p>
    </div>
  </div>

</footer>

templates/base/menu.html
<header class="menus">
  <div class="container">
    <div
      class="
        row
        justify-content-lg-between justify-content-center
        py-3
        align-items-center
      "
    >
      <div class="col-2 text-center">
        <h1><a href="#" class="text-dark website-title">Divertiland</a></h1>
        <img src="static/assets/img/logo.jpg" alt="" />
      </div>

      <div class="col-auto">
        <ul class="nav">
          <li class="nav-item">
            <a href="{% url 'index' %}" class="nav-link">
              Home
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'atraccion:lista' %}" class="nav-link">
              Atraccciones
            </a>
          </li>
          <li class="nav-item">
            <a
              href="https://api.whatsapp.com/send/?phone=573008392839&text=Hola%20vengo%20de%20Divertiland&app_absent=0"
              class="nav-link">
              Contacto
            </a>
          </li>
          {% if user.is_authenticated %} {% if user.is_staff %}
          <li class="nav-item">
            <a href="{% url 'venta:historial-admin' %}" class="nav-link">
              Lista de Carritos
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'admin:index' %}" class="nav-link">
              Admin
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a href="{% url 'venta:historial' %}" class="nav-link">
              Historial de Compras
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'venta:carrito' carrito.pk  %}" class="nav-link">
              Carrito ({{ cantidadItems }})
            </a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a href="{% url 'usuario:logout' %}" class="nav-link">
              Cerrar Sesión
            </a>
          </li>
          {% else %}
          <li class="nav-item botones-registro">
            <a href="{% url 'usuario:login' %}" class="nav-link">
              Iniciar Sesión
            </a>

            <a href="{% url 'usuario:registrar'%}" class="nav-link">
              Registrar
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>


</header>

templates/base/nav-bar.html
<header>
  <div class="container">
    <div class="row justify-content-lg-between justify-content-center py-3 align-items-center">

      <div class="col-2  text-center ">
        <h1><a href="#" class="text-dark website-title">Divertiland</a></h1>
      </div>

      <div class="col-auto ">
        <ul class="nav">
          <li class="nav-item">
            <a href="#" class="nav-link active">Home</a>
          </li>

          <li class="nav-item">
            <a href="#" class="nav-link">Atraccciones</a>
          </li>

          <li class="nav-item">
            <a href="#" class="nav-link">Contacto</a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">Carrito</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'usuario:logout' %}" class="nav-link">Cerrar Sesión</a>
            </li>
          {% else %}
            <li class="nav-item botones-registro">
              <a href="{% url 'usuario:login' %}" class="nav-link">Iniciar Sesión</a>

              <a href="{% url 'usuario:registrar'%}" class="nav-link ">Registrar</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </div>
</header>
<style>
  .botones-registro a{
    display: inline-block;
  }
</style>